/*
 * UnremittedCollectionSummaryPage.java
 *
 * Created on January 22, 2012, 9:32 AM
 */

package etracs2.tc.collection;

import com.rameses.rcp.ui.annotations.StyleSheet;
import java.math.BigDecimal;

/**
 *
 * @author  arnelretiza
 */
@StyleSheet("etracs2/tc/collection/UnremittedCollectionSummaryPage.style")
public class UnremittedCollectionSummaryPage extends javax.swing.JPanel {
    
    /** Creates new form BatchCaptureInitPage */
    public UnremittedCollectionSummaryPage() {
        initComponents();  
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        formPanel2 = new com.rameses.rcp.util.FormPanel();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        xRadio1 = new com.rameses.rcp.control.XRadio();
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xRadio2 = new com.rameses.rcp.control.XRadio();
        formPanel5 = new com.rameses.rcp.util.FormPanel();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        formPanel4 = new com.rameses.rcp.util.FormPanel();
        xLabel5 = new com.rameses.rcp.control.XLabel();
        xLabel6 = new com.rameses.rcp.control.XLabel();
        xLabel7 = new com.rameses.rcp.control.XLabel();
        xButton1 = new com.rameses.rcp.control.XButton();
        formPanel3 = new com.rameses.rcp.util.FormPanel();
        xNumberField2 = new com.rameses.rcp.control.XNumberField();
        xNumberField3 = new com.rameses.rcp.control.XNumberField();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Cash Tendered Info");
        formPanel2.setBorder(xTitledBorder1);
        formPanel2.setCaptionWidth(135);
        xNumberField1.setCaption("Cash Tendered");
        xNumberField1.setFieldType(BigDecimal.class);
        xNumberField1.setFont(new java.awt.Font("Arial", 1, 18));
        xNumberField1.setIndex(5);
        xNumberField1.setMinimumSize(new java.awt.Dimension(11, 30));
        xNumberField1.setName("cashtendered");
        xNumberField1.setPattern("#,##0.00");
        xNumberField1.setPreferredSize(new java.awt.Dimension(200, 28));
        formPanel2.add(xNumberField1);

        xLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        xLabel4.setForeground(new java.awt.Color(204, 0, 0));
        xLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel4.setCaption("Change");
        xLabel4.setFont(new java.awt.Font("Arial", 1, 18));
        xLabel4.setName("entity.change");
        xLabel4.setPadding(new java.awt.Insets(1, 3, 1, 3));
        xLabel4.setPreferredSize(new java.awt.Dimension(200, 28));
        formPanel2.add(xLabel4);

        xPanel1.setLayout(null);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder2 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder2.setTitle("Collection Information");
        xPanel1.setBorder(xTitledBorder2);
        xRadio1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xRadio1.setText("By Series No");
        xRadio1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xRadio1.setName("entity.type");
        xRadio1.setOptionValue("byseries");
        xPanel1.add(xRadio1);
        xRadio1.setBounds(10, 60, 270, 20);

        formPanel1.setCaptionPadding(new java.awt.Insets(0, 0, 0, 5));
        formPanel1.setCaptionWidth(100);
        formPanel1.setPadding(new java.awt.Insets(0, 0, 5, 5));
        xComboBox2.setCaption("Select AF Control");
        xComboBox2.setCaptionWidth(130);
        xComboBox2.setDepends(new String[] {"entity.type"});
        xComboBox2.setDynamic(true);
        xComboBox2.setExpression("#{afid}");
        xComboBox2.setFont(new java.awt.Font("Arial", 1, 14));
        xComboBox2.setImmediate(true);
        xComboBox2.setIndex(-100);
        xComboBox2.setItems("afcontrollist");
        xComboBox2.setName("entity.afcontrol");
        xComboBox2.setPreferredSize(new java.awt.Dimension(200, 26));
        xComboBox2.setRequired(true);
        formPanel1.add(xComboBox2);

        xPanel1.add(formPanel1);
        formPanel1.setBounds(10, 30, 332, 28);

        xRadio2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xRadio2.setText("By Payor Name");
        xRadio2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xRadio2.setName("entity.type");
        xRadio2.setOptionValue("bytaxpayer");
        xPanel1.add(xRadio2);
        xRadio2.setBounds(10, 142, 270, 18);

        formPanel5.setCaptionWidth(100);
        formPanel5.setPadding(new java.awt.Insets(3, 0, 5, 5));
        xTextField3.setCaption("Payor Name");
        xTextField3.setCaptionWidth(115);
        xTextField3.setDepends(new String[] {"entity.type"});
        xTextField3.setFont(new java.awt.Font("Arial", 0, 14));
        xTextField3.setName("entity.payorname");
        xTextField3.setPreferredSize(new java.awt.Dimension(200, 24));
        formPanel5.add(xTextField3);

        xPanel1.add(formPanel5);
        formPanel5.setBounds(26, 160, 330, 30);

        formPanel4.setCaptionWidth(115);
        formPanel4.setPadding(new java.awt.Insets(5, 0, 5, 0));
        xLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        xLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel5.setCaption("Cash");
        xLabel5.setFont(new java.awt.Font("Arial", 1, 14));
        xLabel5.setName("entity.cash");
        xLabel5.setPadding(new java.awt.Insets(1, 3, 1, 3));
        xLabel5.setPreferredSize(new java.awt.Dimension(200, 24));
        formPanel4.add(xLabel5);

        xLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        xLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel6.setCaption("Check");
        xLabel6.setFont(new java.awt.Font("Arial", 1, 14));
        xLabel6.setName("entity.otherpayment");
        xLabel6.setPadding(new java.awt.Insets(1, 3, 1, 3));
        xLabel6.setPreferredSize(new java.awt.Dimension(200, 24));
        formPanel4.add(xLabel6);

        xLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        xLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel7.setCaption("Total Amount");
        xLabel7.setFont(new java.awt.Font("Arial", 1, 14));
        xLabel7.setName("entity.totalamount");
        xLabel7.setPadding(new java.awt.Insets(1, 3, 1, 3));
        xLabel7.setPreferredSize(new java.awt.Dimension(200, 24));
        formPanel4.add(xLabel7);

        xPanel1.add(formPanel4);
        formPanel4.setBounds(26, 192, 320, 88);

        xButton1.setText("Compute");
        xButton1.setName("compute");
        xPanel1.add(xButton1);
        xButton1.setBounds(250, 280, 90, 26);

        formPanel3.setCaptionWidth(100);
        formPanel3.setPadding(new java.awt.Insets(2, 0, 5, 5));
        xNumberField2.setCaption("From Series");
        xNumberField2.setCaptionWidth(115);
        xNumberField2.setDepends(new String[] {"entity.type"});
        xNumberField2.setFieldType(Long.class);
        xNumberField2.setFont(new java.awt.Font("Arial", 0, 14));
        xNumberField2.setName("entity.fromseries");
        xNumberField2.setPreferredSize(new java.awt.Dimension(200, 24));
        formPanel3.add(xNumberField2);

        xNumberField3.setCaption("To Series");
        xNumberField3.setCaptionWidth(115);
        xNumberField3.setDepends(new String[] {"entity.type"});
        xNumberField3.setFieldType(Long.class);
        xNumberField3.setFont(new java.awt.Font("Arial", 0, 14));
        xNumberField3.setName("entity.toseries");
        xNumberField3.setPreferredSize(new java.awt.Dimension(200, 24));
        formPanel3.add(xNumberField3);

        xPanel1.add(formPanel3);
        formPanel3.setBounds(26, 82, 320, 57);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, formPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, xPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 359, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(xPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 320, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(formPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.util.FormPanel formPanel2;
    private com.rameses.rcp.util.FormPanel formPanel3;
    private com.rameses.rcp.util.FormPanel formPanel4;
    private com.rameses.rcp.util.FormPanel formPanel5;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XLabel xLabel5;
    private com.rameses.rcp.control.XLabel xLabel6;
    private com.rameses.rcp.control.XLabel xLabel7;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XNumberField xNumberField2;
    private com.rameses.rcp.control.XNumberField xNumberField3;
    private com.rameses.rcp.control.XPanel xPanel1;
    private com.rameses.rcp.control.XRadio xRadio1;
    private com.rameses.rcp.control.XRadio xRadio2;
    private com.rameses.rcp.control.XTextField xTextField3;
    // End of variables declaration//GEN-END:variables
    
}
