/*
 * AccountPage.java
 *
 * Created on February 27, 2011, 12:48 PM
 */

package etracs2.tc.master.ui;

import com.rameses.client.ui.template.DefaultFormPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author  jzamss
 */
@StyleSheet
@Template(DefaultFormPage.class)
public class BankAcctPage extends javax.swing.JPanel {
    
    /** Creates new form AccountPage */
    public BankAcctPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xComboBox3 = new com.rameses.rcp.control.XComboBox();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        xTextField5 = new com.rameses.rcp.control.XTextField();
        xSeparator1 = new com.rameses.rcp.control.XSeparator();
        xTextField6 = new com.rameses.rcp.control.XTextField();
        xTextField7 = new com.rameses.rcp.control.XTextField();
        xTextField8 = new com.rameses.rcp.control.XTextField();

        setPreferredSize(new java.awt.Dimension(542, 498));

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Bank Account Information");
        formPanel1.setBorder(xTitledBorder1);
        xTextField1.setCaption("Account No.");
        xTextField1.setCaptionWidth(100);
        xTextField1.setDepends(new String[] {"selectedItem"});
        xTextField1.setName("entity.acctno");
        xTextField1.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField1.setRequired(true);
        formPanel1.add(xTextField1);

        xTextField3.setCaption("Account Name");
        xTextField3.setCaptionWidth(100);
        xTextField3.setDepends(new String[] {"selectedItem"});
        xTextField3.setName("entity.bankacctname");
        xTextField3.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField3.setRequired(true);
        formPanel1.add(xTextField3);

        xComboBox1.setCaption("Account Type");
        xComboBox1.setCaptionWidth(100);
        xComboBox1.setDepends(new String[] {"selectedItem"});
        xComboBox1.setItems("accttypes");
        xComboBox1.setName("entity.accttype");
        xComboBox1.setPreferredSize(new java.awt.Dimension(0, 22));
        xComboBox1.setRequired(true);
        formPanel1.add(xComboBox1);

        xComboBox2.setCaption("Fund");
        xComboBox2.setCaptionWidth(100);
        xComboBox2.setDepends(new String[] {"selectedItem"});
        xComboBox2.setItems("funds");
        xComboBox2.setName("entity.fund");
        xComboBox2.setPreferredSize(new java.awt.Dimension(0, 22));
        xComboBox2.setRequired(true);
        formPanel1.add(xComboBox2);

        xComboBox3.setCaption("Currency");
        xComboBox3.setCaptionWidth(100);
        xComboBox3.setDepends(new String[] {"selectedItem"});
        xComboBox3.setItems("currencylist");
        xComboBox3.setName("entity.currency");
        xComboBox3.setPreferredSize(new java.awt.Dimension(0, 22));
        xComboBox3.setRequired(true);
        formPanel1.add(xComboBox3);

        xLookupField1.setCaption("Bank Code");
        xLookupField1.setCaptionWidth(100);
        xLookupField1.setDepends(new String[] {"selectedItem"});
        xLookupField1.setExpression("#{bankcode}");
        xLookupField1.setHandler("lookupBank");
        xLookupField1.setName("bank");
        xLookupField1.setPreferredSize(new java.awt.Dimension(0, 19));
        xLookupField1.setRequired(true);
        formPanel1.add(xLookupField1);

        xTextField4.setCaption("Bank Name");
        xTextField4.setCaptionWidth(100);
        xTextField4.setDepends(new String[] {"selectedItem", "bank"});
        xTextField4.setName("entity.bankname");
        xTextField4.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField4.setReadonly(true);
        formPanel1.add(xTextField4);

        xTextField5.setCaption("Branch Name");
        xTextField5.setCaptionWidth(100);
        xTextField5.setDepends(new String[] {"selectedItem", "bank"});
        xTextField5.setName("entity.branchname");
        xTextField5.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField5.setReadonly(true);
        formPanel1.add(xTextField5);

        xSeparator1.setCaption("Deposit Slip Report Format");
        xSeparator1.setCaptionFont(new java.awt.Font("Tahoma", 1, 11));
        xSeparator1.setCaptionWidth(500);
        xSeparator1.setCellPadding(new java.awt.Insets(15, 0, 5, 0));
        xSeparator1.setPreferredSize(new java.awt.Dimension(0, 20));
        xSeparator1.setShowCaption(true);
        org.jdesktop.layout.GroupLayout xSeparator1Layout = new org.jdesktop.layout.GroupLayout(xSeparator1);
        xSeparator1.setLayout(xSeparator1Layout);
        xSeparator1Layout.setHorizontalGroup(
            xSeparator1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );
        xSeparator1Layout.setVerticalGroup(
            xSeparator1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 20, Short.MAX_VALUE)
        );
        formPanel1.add(xSeparator1);

        xTextField6.setText("entity.cashreport");
        xTextField6.setCaption("Cash");
        xTextField6.setCaptionWidth(120);
        xTextField6.setDepends(new String[] {"selectedItem"});
        xTextField6.setName("entity.cashreport");
        xTextField6.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField6.setTextCase(com.rameses.rcp.constant.TextCase.LOWER);
        formPanel1.add(xTextField6);

        xTextField7.setText("entity.cashbreakdownreport");
        xTextField7.setCaption("Cash Breakdown");
        xTextField7.setCaptionWidth(120);
        xTextField7.setDepends(new String[] {"selectedItem"});
        xTextField7.setName("entity.cashbreakdownreport");
        xTextField7.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField7.setTextCase(com.rameses.rcp.constant.TextCase.LOWER);
        formPanel1.add(xTextField7);

        xTextField8.setText("entity.checkreport");
        xTextField8.setCaption("Check");
        xTextField8.setCaptionWidth(120);
        xTextField8.setDepends(new String[] {"selectedItem"});
        xTextField8.setName("entity.checkreport");
        xTextField8.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField8.setTextCase(com.rameses.rcp.constant.TextCase.LOWER);
        formPanel1.add(xTextField8);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 496, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 325, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XComboBox xComboBox3;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    private com.rameses.rcp.control.XSeparator xSeparator1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField3;
    private com.rameses.rcp.control.XTextField xTextField4;
    private com.rameses.rcp.control.XTextField xTextField5;
    private com.rameses.rcp.control.XTextField xTextField6;
    private com.rameses.rcp.control.XTextField xTextField7;
    private com.rameses.rcp.control.XTextField xTextField8;
    // End of variables declaration//GEN-END:variables
    
}
