/*
 * AccountPage.java
 *
 * Created on February 27, 2011, 12:48 PM
 */

package etracs2.tc.master.ui;

import com.rameses.client.ui.template.DefaultFormPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author  jzamss
 */
@StyleSheet
@Template(DefaultFormPage.class)
public class IncomeAcctPage extends javax.swing.JPanel {
    
    /** Creates new form AccountPage */
    public IncomeAcctPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xComboBox4 = new com.rameses.rcp.control.XComboBox();
        xSeparator1 = new com.rameses.rcp.control.XSeparator();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();
        xActionTextField4 = new com.rameses.rcp.control.XActionTextField();
        xLookupField2 = new com.rameses.rcp.control.XLookupField();
        xActionTextField5 = new com.rameses.rcp.control.XActionTextField();
        formPanel2 = new com.rameses.rcp.util.FormPanel();
        xComboBox3 = new com.rameses.rcp.control.XComboBox();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xCheckBox1 = new com.rameses.rcp.control.XCheckBox();

        setPreferredSize(new java.awt.Dimension(542, 498));

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Account Details");
        formPanel1.setBorder(xTitledBorder1);
        formPanel1.setCaptionWidth(95);
        xLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel1.setCaption("State");
        xLabel1.setDepends(new String[] {"selectedItem"});
        xLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        xLabel1.setName("entity.docstate");
        xLabel1.setPreferredSize(new java.awt.Dimension(150, 18));
        formPanel1.add(xLabel1);

        xTextField1.setCaption("Acct No.");
        xTextField1.setDepends(new String[] {"selectedItem"});
        xTextField1.setIndex(-10);
        xTextField1.setName("entity.acctno");
        xTextField1.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel1.add(xTextField1);

        xTextField2.setCaption("Title");
        xTextField2.setDepends(new String[] {"selectedItem"});
        xTextField2.setName("entity.accttitle");
        xTextField2.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField2.setRequired(true);
        formPanel1.add(xTextField2);

        xComboBox1.setCaption("Fund");
        xComboBox1.setDepends(new String[] {"selectedItem"});
        xComboBox1.setImmediate(true);
        xComboBox1.setItems("fundList");
        xComboBox1.setName("entity.fundname");
        xComboBox1.setPreferredSize(new java.awt.Dimension(200, 22));
        xComboBox1.setRequired(true);
        formPanel1.add(xComboBox1);

        xComboBox2.setCaption("System Type");
        xComboBox2.setDepends(new String[] {"selectedItem"});
        xComboBox2.setImmediate(true);
        xComboBox2.setItems("systemTypeList");
        xComboBox2.setName("entity.systype");
        xComboBox2.setPreferredSize(new java.awt.Dimension(200, 22));
        xComboBox2.setRequestFocusEnabled(false);
        formPanel1.add(xComboBox2);

        xComboBox4.setCaption("Grouping");
        xComboBox4.setDepends(new String[] {"selectedItem"});
        xComboBox4.setImmediate(true);
        xComboBox4.setItems("incomeaccountgrouplist");
        xComboBox4.setName("entity.groupid");
        xComboBox4.setPreferredSize(new java.awt.Dimension(200, 22));
        xComboBox4.setRequestFocusEnabled(false);
        formPanel1.add(xComboBox4);

        xSeparator1.setPreferredSize(new java.awt.Dimension(0, 20));
        formPanel1.add(xSeparator1);

        xLookupField1.setCaption("NGAS Account");
        xLookupField1.setDepends(new String[] {"selectedItem"});
        xLookupField1.setExpression("#{accttitle}");
        xLookupField1.setHandler("lookupNGAS");
        xLookupField1.setName("ngas");
        xLookupField1.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel1.add(xLookupField1);

        xActionTextField4.setActionName("lookupNgasSubAcct");
        xActionTextField4.setCaption("    Sub Account");
        xActionTextField4.setDepends(new String[] {"selecetedItem", "entity.ngastitle"});
        xActionTextField4.setName("entity.ngassubaccttitle");
        xActionTextField4.setPreferredSize(new java.awt.Dimension(0, 20));
        formPanel1.add(xActionTextField4);

        xLookupField2.setCaption("SRE Account");
        xLookupField2.setDepends(new String[] {"selectedItem"});
        xLookupField2.setExpression("#{accttitle}");
        xLookupField2.setHandler("lookupSRE");
        xLookupField2.setName("sre");
        xLookupField2.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel1.add(xLookupField2);

        xActionTextField5.setActionName("lookupSreSubAcct");
        xActionTextField5.setCaption("    Sub Account");
        xActionTextField5.setDepends(new String[] {"selectedItem", "entity.sretitle"});
        xActionTextField5.setName("entity.sresubaccttitle");
        xActionTextField5.setPreferredSize(new java.awt.Dimension(0, 20));
        formPanel1.add(xActionTextField5);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder2 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder2.setTitle("Optional Settings");
        formPanel2.setBorder(xTitledBorder2);
        xComboBox3.setCaption("Amount Type");
        xComboBox3.setCaptionWidth(100);
        xComboBox3.setDepends(new String[] {"selectedItem"});
        xComboBox3.setImmediate(true);
        xComboBox3.setItems("amountTypeList");
        xComboBox3.setName("entity.amounttype");
        xComboBox3.setPreferredSize(new java.awt.Dimension(120, 22));
        xComboBox3.setRequestFocusEnabled(false);
        formPanel2.add(xComboBox3);

        xNumberField1.setCaption("Default Value");
        xNumberField1.setCaptionWidth(100);
        xNumberField1.setDepends(new String[] {"selectedItem", "entity.amounttype"});
        xNumberField1.setName("entity.defaultvalue");
        xNumberField1.setPreferredSize(new java.awt.Dimension(120, 19));
        formPanel2.add(xNumberField1);

        xTextField3.setCaption("Rule Code");
        xTextField3.setCaptionWidth(100);
        xTextField3.setDepends(new String[] {"selectedItem"});
        xTextField3.setName("entity.acctcode");
        xTextField3.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel2.add(xTextField3);

        xCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox1.setCaption(" Allow Discount?");
        xCheckBox1.setCaptionWidth(100);
        xCheckBox1.setCheckValue(1);
        xCheckBox1.setDepends(new String[] {"selectedItem"});
        xCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox1.setName("entity.allowdiscount");
        xCheckBox1.setUncheckValue(0);
        formPanel2.add(xCheckBox1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, formPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, formPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 282, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(formPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.util.FormPanel formPanel2;
    private com.rameses.rcp.control.XActionTextField xActionTextField4;
    private com.rameses.rcp.control.XActionTextField xActionTextField5;
    private com.rameses.rcp.control.XCheckBox xCheckBox1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XComboBox xComboBox3;
    private com.rameses.rcp.control.XComboBox xComboBox4;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    private com.rameses.rcp.control.XLookupField xLookupField2;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XSeparator xSeparator1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField3;
    // End of variables declaration//GEN-END:variables
    
}
